---
title: "MATH-650 Assignment 6"
author: 'Saket Choudhary (USCID: 2170058637) (skchoudh@usc.edu)'
date: "09/15/2015"
output:
  html_document:
    keep_md: yes
  pdf_document: default
---

# Problem 19
```{r}
pH.data <- read.csv('case0702.csv', header=T)
logT <- log(pH.data$Time)
pH.data$logT <- logT
n <- nrow(pH.data)
```

Simple linear regression model for $log(pH)$ is given by:
$$
pH = \beta_0 + \beta_1log(T)
$$


### Part (a)
```{r}
fit <- lm(pH~logT, data=pH.data)
s <- summary(fit)
b0 <- fit$coefficients[1]
b1 <- fit$coefficients[2]
se0 <- s$coefficients[3]
se1 <- s$coefficients[4]
t0 <- s$coefficients[5]
t1 <- s$coefficients[6]
p0 <- s$coefficients[7]
p1 <- s$coefficients[8]
```

Thus, $\beta_0=`r b0`(S.E=`r se0`, p-value=`r p0`)$ and $\beta_1=`r b1`(S.E=`r se1`, p-value=`r p1`)$

### Part (b)

```{r}
Xbar <- mean(log(pH.data$Time))#1.190
sx2 <- var(log(pH.data$Time))#0.6344
mu <- b0 +b1*log(5)

```

Thus, $\hat\mu\{Y|log(5)\} = `r mu`$ and $SE[\hat\mu\{Y|log(5)\}] = `r se`$

### Part (c)

```{r}
sigmahat <- 0.08226
se = sigmahat *sqrt(1/n+(log(5)-Xbar)^2/(n-1*sx2))
```


# Problem 25

