
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.8'

_lr_method = 'LALR'

_lr_signature = '5B675055957AA5B4BFB55E6752FF63FF'
    
_lr_action_items = {'IMPLY':([1,2,5,7,9,10,11,12,],[-6,6,8,8,-3,-4,-5,-2,]),'RPAREN':([1,7,9,10,11,12,],[-6,11,-3,-4,-5,-2,]),'LPAREN':([0,4,6,],[4,4,4,]),'PREMISE':([0,4,6,8,],[1,1,1,1,]),'$end':([1,3,5,9,10,11,12,],[-6,0,-1,-3,-4,-5,-2,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expression':([0,4,6,],[5,7,10,]),'premise':([0,4,6,8,],[2,2,9,12,]),'statement':([0,],[3,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> statement","S'",1,None,None,None),
  ('statement -> expression','statement',1,'p_statement','parser.py',58),
  ('expression -> expression IMPLY premise','expression',3,'p_expression_imply','parser.py',64),
  ('expression -> premise IMPLY premise','expression',3,'p_expression_imply','parser.py',65),
  ('expression -> premise IMPLY expression','expression',3,'p_expression_imply','parser.py',66),
  ('expression -> LPAREN expression RPAREN','expression',3,'p_expression_premise','parser.py',71),
  ('premise -> PREMISE','premise',1,'p_premise_expr','parser.py',75),
]
